package com.kundu.customerstatement.exception;

import java.lang.reflect.Method;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.aop.interceptor.AsyncUncaughtExceptionHandler;

/**
 * This class is used to handle the exceptions generated by different async controllers. With this centralized approach, there is a chance to provide
 * a similar behavior for different errors generated from different sources.
 * 
 * @author ukundukan
 *
 */
public class AsyncExceptionHandler implements AsyncUncaughtExceptionHandler {

	private static final Logger myLogger = LoggerFactory.getLogger(AsyncExceptionHandler.class);

	@Override
	public void handleUncaughtException(Throwable ex, Method method, Object... params) {
		myLogger.error(String.format("Async exception. Method: {}, Params: {}", method, params), ex);
	}

}
